import{i as d,S as f}from"./assets/vendor-3fe00192.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();const m="45375111-d1e8183fd09326f55157dfb1e",y="https://pixabay.com/api/";async function p(e,o=1,s=12){const a=`${y}?key=${m}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`;try{const t=await(await fetch(a)).json();if(t.totalHits===0){const n=document.createElement("div");throw n.className="error-message",n.textContent="Sorry, there are no images matching your search query. Please, try again!",document.body.appendChild(n),new Error(n.textContent)}return t}catch(r){throw r}}function g(e){const o=document.querySelector(".gallery"),s=e.map(a=>h(a)).join("");o.insertAdjacentHTML("beforeend",s)}function h({webformatURL:e,largeImageURL:o,tags:s,likes:a,views:r,comments:t,downloads:n}){return`
    <a href="${o}" class="gallery__item">
      <img src="${e}" alt="${s}" loading="lazy" class="gallery__image"/>
      <div class="gallery__info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${r}</p>
        <p><b>Comments:</b> ${t}</p>
        <p><b>Downloads:</b> ${n}</p>
      </div>
    </a>
  `}function b(){const e=document.querySelector(".gallery");e.innerHTML=""}function i(e,o="info"){d[o]({title:o.charAt(0).toUpperCase()+o.slice(1),message:e,position:"topRight"})}function w(){document.querySelector(".loader").classList.add("visible")}function L(){document.querySelector(".loader").classList.remove("visible")}const v=document.querySelector("#search-form");let c="",l=1;v.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.currentTarget.elements.searchQuery.value.trim(),c===""){i("Please enter a search query","warning");return}b(),l=1,await u()});async function u(){try{w();const e=await p(c,l);if(e.hits.length===0){i("Sorry, there are no images matching your search query. Please, try again!","error");return}g(e.hits),e.totalHits>12&&q(),new f(".gallery a").refresh()}catch(e){i(e.message,"error")}finally{L()}}function q(){const e={root:null,rootMargin:"0px",threshold:.5};new IntersectionObserver(async s=>{s[0].isIntersecting&&(l+=1,await u())},e).observe(document.querySelector(".load-more"))}
//# sourceMappingURL=commonHelpers.js.map
