import{S as u,i as f}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const d="45375111-d1e8183fd09326f55157dfb1e",m="https://pixabay.com/api/";async function p(n,t=1,s=12){const r=`${m}?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;try{const e=await fetch(r);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error("Error fetching images:",e),e}}let a=null;function y(n){const t=document.querySelector(".gallery");t.innerHTML="";const s=n.map(r=>`
            <a class="gallery__item" href="${r.largeImageURL}">
                <img class="gallery__image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
                <div class="info">
                    <p class="info-item"><b>Likes:</b> ${r.likes}</p>
                    <p class="info-item"><b>Views:</b> ${r.views}</p>
                    <p class="info-item"><b>Comments:</b> ${r.comments}</p>
                    <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
                </div>
            </a>`).join("");t.insertAdjacentHTML("beforeend",s),a?a.refresh():a=new u(".gallery a")}function h(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function L(){f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const c=document.querySelector("#search-form"),b=document.querySelector(".gallery");let l=1;const w=12;c.addEventListener("submit",async n=>{n.preventDefault();const t=c.querySelector('input[name="searchQuery"]').value.trim();if(t){l=1,b.innerHTML="",h();try{const s=await p(t,l,w);s.hits.length===0?L():y(s.hits)}catch(s){console.error("Error:",s)}finally{g()}}});
//# sourceMappingURL=commonHelpers.js.map
